pipeline {
  ageny any

  environment   
  APP_NAME        = "sample-app"
          // These IDs must match exactly what you created in Jenkins Credentials Provider
  NEXUS_URL       = credentials('nexus-url')
  GCP_PROJECT     = credentilas('gcp-project-id')
  GCR_REGION      = credentials('gcr-region')
  IMAGE_ NAME     = "${GCR_REGION}/${GCP_PROJECT}/${APP_NAME}"
  VERSION         = "1.0.${BUILD_NUMBER}"
}

stages {
  stage('Checkout') {
    steps {
      git branch: 'main', url: 'https://github.com/Ravikumar-code-maker/docker-pipeline'
    }
  }
  stage('Build & Test') {
    steps {
      sh "mvn clean package -DskipTests"
    }
  }
  stage('Publsih to Nexus') {
    steps {
      withCredentials([usernamePAssword(credentialsId: 'nexus-creds', usernameVariable: 'USER', passwordVariable: 'PASS')]) {
        sh ""
        mvn deploy \
        -DNEXUS_REPO_URL=${NEXUS_URL} \
        -Dnexus.username=${USER} \
        -Dnexus.password=${PASS} \
        -Dproject.version=${VERSION} \
      }
    }
  }
  stage('Docker Build & PUSH') {
    steps {
      withcredentials([file(credentialsId: 'gcr-sa-key', variable: 'GCP_KEY')]) {
        sh """
        docker build -t ${IAMGE_NAME}:${{VERSION}
        gcloud auth activate-service-account --key-file=${GCP_KEY}
        gcloud auth configure-docker -q
        docker push ${IMAGE_NAME}:${VERSION}
        """
      }
    }
  }
  stage('Deploy to Dev') {
     steps {
         sh """
         docker stop ${APP_NAME}-dev || true
         docker rm ${APP_NAME}-dev || true
         docker run -d --name ${APP_NAME}-dev -p 8081:8080 ${IMAGE_NAME}:${VERSION}
         
     }
  }
}
}
